console.log('Hello from ts');
var myString;
var myNum;
var myBool;
var myVar;
// Has to be an array of strings
var strArr;
var striArra;
var numArr;
var boolArr;
var strNumTuple;
myString = 'Hello World';
myNum = 22;
myBool = true;
myVar = 5;
strArr = ['Hello', 'World'];
striArra = ['Hi'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['Hello', 4, 3, 4];
var myVoid = null;
var myNull = undefined;
var myUndefined = undefined;
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(myVar);
console.log(strArr);
console.log(striArra);
console.log(numArr);
console.log(boolArr);
console.log(strNumTuple);
console.log(myVoid);
console.log(myNull);
console.log(myUndefined);
